# Generated by Django 4.0 on 2022-02-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='donor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.donor'),
        ),
        migrations.AddField(
            model_name='organ',
            name='recipient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.recipient'),
        ),
    ]
